In [1]:
import pandas as pd
import numpy as np

In [4]:
movies=pd.read_csv("/content/movies.csv",usecols=["movieId","title"])
movies.head()

   movieId                               title
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

In [8]:
rating=pd.read_csv("/content/ratings.csv",usecols=["userId","movieId","rating"])
rating.head()

   userId  movieId  rating
0       1        1     4.0
1       1        3     4.0
2       1        6     4.0
3       1       47     5.0
4       1       50     5.0

In [9]:
rating.shape

(100836, 3)

In [12]:
reating_users=rating.pivot(index="movieId",columns="userId",values="rating").fillna(0)
reating_users.head()

userId,1,2,3,4,5,6,7,8,9,10,...,601,602,603,604,605,606,607,608,609,610
movieId,,,,,,,,,,,,,,,,,,,,,
1,4.0,0.0,0.0,0.0,4.0,0.0,4.5,0.0,0.0,0.0,...,4.0,0.0,4.0,3.0,4.0,2.5,4.0,2.5,3.0,5.0
2,0.0,0.0,0.0,0.0,0.0,4.0,0.0,4.0,0.0,0.0,...,0.0,4.0,0.0,5.0,3.5,0.0,0.0,2.0,0.0,0.0
3,4.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
from scipy.sparse import csr_matrix

In [14]:
mat_movies=csr_matrix(reating_users.values)

In [15]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(metric="cosine",algorithm="brute",n_neighbors=20)
model.fit(mat_movies)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=20)

In [18]:
!pip install fuzzywuzzy
from fuzzywuzzy import process

Collecting fuzzywuzzy
  Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl.metadata (4.9 kB)
Downloading fuzzywuzzy-0.18.0-py2.py3-none-any.whl (18 kB)
Installing collected packages: fuzzywuzzy
Successfully installed fuzzywuzzy-0.18.0

/usr/local/lib/python3.12/dist-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [31]:
def recommender(movie_name,data,n):
  idx=process.extractOne(movie_name,movies["title"])[2]
  print("Movie Selected: ",movies["title"][idx],"Index: ",idx)
  print("Searching for recommendation.....")
  distance,indices=model.kneighbors(mat_movies[idx],n_neighbors=20)
  for i in indices:
    print(movies["title"][i].where(i!=idx))

In [32]:
recommender("toy story",mat_movies,10)

Movie Selected:  Toy Story (1995) Index:  0
Searching for recommendation.....
0                                                     NaN
2353                                 'night Mother (1986)
418                                  Jurassic Park (1993)
615                  Independence Day (a.k.a. ID4) (1996)
224             Star Wars: Episode IV - A New Hope (1977)
314                                   Forrest Gump (1994)
322                                 Lion King, The (1994)
910     Once Upon a Time in the West (C'era una volta ...
546                            Mission: Impossible (1996)
963                                           Diva (1981)
968                           Arsenic and Old Lace (1944)
3189            Rififi (Du rififi chez les hommes) (1955)
506                                        Aladdin (1992)
123                                      Apollo 13 (1995)
257                                   Pulp Fiction (1994)
897                 Cheech and Chong's Up in Smoke (1978)
815            Willy Wonka & the Chocolate Factory (1971)
1182                                          Fall (1997)
31              Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
277                      Shawshank Redemption, The (1994)
Name: title, dtype: object

In [34]:
recommender("iron man",mat_movies,10)

Movie Selected:  Iron Man (2008) Index:  6743
Searching for recommendation.....
6743                                            NaN
7197                                  Garage (2007)
7195                        Merry Madagascar (2009)
7354                             A-Team, The (2010)
6726                         Superhero Movie (2008)
7137                         Thirst (Bakjwi) (2009)
7026                                 Scorpio (1973)
7571                                 Win Win (2011)
3880                  Look Who's Talking Now (1993)
6388    After the Wedding (Efter brylluppet) (2006)
7601                       Idiots and Angels (2008)
6755                Nina's Heavenly Delights (2006)
7022                                   Earth (2007)
7338                          Blue Valentine (2010)
4421                         What's Up, Doc? (1972)
6195                             Silent Hill (2006)
5885                                   Crash (2004)
3740                              Motel Hell (1980)
7378           Serbian Film, A (Srpski film) (2010)
7289                            Generation X (1996)
Name: title, dtype: object